# Generated by Django 4.2.1 on 2023-05-16 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Acta N°')),
                ('pub_date', models.DateTimeField(verbose_name='Data publish')),
                ('process_text', models.CharField(max_length=200)),
                ('type_meet', models.CharField(max_length=20)),
                ('hour', models.CharField(max_length=200)),
                ('next_meet', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data publish')),
                ('observations', models.CharField(max_length=200)),
                ('commitment', models.CharField(max_length=200)),
                ('control', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_job', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('attended', models.CharField(max_length=200)),
                ('approve', models.CharField(max_length=200)),
                ('asset', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibledevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.user')),
            ],
        ),
        migrations.CreateModel(
            name='Responsiblecommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.user')),
            ],
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=200)),
                ('tittle', models.CharField(max_length=200)),
                ('agreements', models.CharField(max_length=200)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.act')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.act')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.user')),
            ],
        ),
    ]
